spring:
  application:
    name: Workipedia

  profiles:
    default: local

  config:
    import: optional:file:.env[.properties]

  flyway:
    enabled: true

  output:
    ansi:
      enabled: always

ai-sync:
  worker:
    cleanup-cron: "0 0 3 1 * *"
    retention-days: 365

logging:
  level:
    '[org.springframework.web]': info
    '[org.springframework.security]': info
    '[org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver]': error
    '[org.mariadb.jdbc.client.impl]': info
    '[org.springframework.data.redis]': info
    '[io.lettuce.core]': info

management:
  health:
    mail:
      enabled: false

  endpoints:
    web:
      exposure:
        include: health,info,metrics

  endpoint:
    health:
      show-details: always

  metrics:
    tags:
      application: Workipedia
