package com.wip.workipedia.admin.domain;

public enum AdminActionType {
	USER_DEACTIVATE, // 유저 비활성화
	WORKI_UPDATE,
	WORKI_DELETE,
	MANUAL_CREATE,
	MANUAL_UPDATE,
	MANUAL_DELETE,
	TICKET_TRANSFER_REQUEST,
	TICKET_ROUTE_OVERRIDE,
	COMMON_QUEUE_ASSIGN,
	KNOWLEDGE_REVIEW,
	KNOWLEDGE_PUBLISH
}
