package com.wip.workipedia.admin.domain;

public enum AdminActionType {
	USER_DEACTIVATE,
	WORKI_READ,
	WORKI_UPDATE,
	WORKI_DELETE,
	MANUAL_UPDATE,
	MANUAL_DELETE,
	TICKET_ASSIGN,
	TICKET_TRANSFER_REQUEST,
	TICKET_ROUTE_OVERRIDE,
	COMMON_QUEUE_ASSIGN,
	KNOWLEDGE_REVIEW,
	KNOWLEDGE_PUBLISH
}
