package com.wip.workipedia.point.domain;

public enum PointReasonType {
	LOGIN,
	WORKI_FIRST_QUESTION_CREATED,
	WORKI_QUESTION_CREATED,
	WORKI_ANSWER_CREATED,
	WORKI_ANSWER_ACCEPTED,
	TICKET_ANSWER_CREATED,
	TICKET_KNOWLEDGE_CREATED
}